#note:  this is saved to my repo for posterity in its current form, but can also be generated by ParseOGP.C if you set the 'build_gnuplot' flag to true
set terminal pdf size 60,30 linewidth 1 font 'Verdana,100'
set output 'all_lines_multi_large.pdf'

area21_0=8.28;area21_212=-900.00;dist21=229.67;  dx21=-56.55;dy21=-222.60;dphi21=-4.4636
area22_0=8.56;area22_212=14.49;dist22=524.03;  dx22=-56.33;dy22=-222.56;dphi22=-1.3043
area23_0=8.77;area23_212=-900.00;dist23=229.49;  dx23=-56.35;dy23=-222.46;dphi23=-4.4643
area24_0=8.56;area24_212=14.86;dist24=524.52;  dx24=-56.33;dy24=-222.56;dphi24=-1.2624
area44_0=8.15;area44_212=14.60;dist44=524.47;  dx44=-56.59;dy44=-222.72;dphi44=-1.2631
area45_0=8.16;area45_212=15.99;dist45=524.51;  dx45=-56.46;dy45=-222.62;dphi45=-1.2622
area46_0=8.17;area46_212=14.60;dist46=524.49;  dx46=-56.46;dy46=-222.61;dphi46=-1.2624
area47_0=8.18;area47_212=14.35;dist47=524.40;  dx47=-56.54;dy47=-222.57;dphi47=-1.2625
area48_0=8.18;area48_212=14.36;dist48=524.40;  dx48=-56.31;dy48=-222.45;dphi48=-1.2626
area49_0=8.29;area49_212=14.56;dist49=524.45;  dx49=-56.47;dy49=-222.56;dphi49=-1.2625
area50_0=8.21;area50_212=14.73;dist50=524.26;  dx50=-56.36;dy50=-222.52;dphi50=-1.2623
area51_0=8.33;area51_212=14.79;dist51=524.56;  dx51=-56.40;dy51=-222.67;dphi51=-1.2624
area52_0=8.13;area52_212=14.59;dist52=524.41;  dx52=-56.39;dy52=-222.92;dphi52=-1.2622
area53_0=8.11;area53_212=14.93;dist53=524.46;  dx53=-56.43;dy53=-222.77;dphi53=-1.2625
area54_0=8.48;area54_212=15.29;dist54=524.50;  dx54=-56.37;dy54=-222.63;dphi54=-1.2619
area55_0=9.25;area55_212=14.64;dist55=524.47;  dx55=-56.31;dy55=-222.70;dphi55=-1.2620
area57_0=8.33;area57_212=15.16;dist57=524.37;  dx57=-56.39;dy57=-222.67;dphi57=-1.2621
area58_0=8.21;area58_212=14.84;dist58=524.41;  dx58=-56.32;dy58=-222.62;dphi58=-1.2621
area59_0=8.01;area59_212=14.77;dist59=524.51;  dx59=-56.41;dy59=-222.58;dphi59=-1.2625
area60_0=8.13;area60_212=14.42;dist60=524.45;  dx60=-56.59;dy60=-222.76;dphi60=-1.2627
area61_0=8.12;area61_212=14.29;dist61=524.34;  dx61=-56.29;dy61=-222.78;dphi61=-1.2617
area62_0=8.26;area62_212=15.03;dist62=524.38;  dx62=-56.71;dy62=-222.75;dphi62=-1.2627
area63_0=8.18;area63_212=14.76;dist63=524.43;  dx63=-56.31;dy63=-222.46;dphi63=-1.2624
area64_0=8.01;area64_212=14.86;dist64=524.55;  dx64=-56.73;dy64=-222.64;dphi64=-1.2630
area65_0=8.14;area65_212=14.69;dist65=524.43;  dx65=-56.60;dy65=-222.72;dphi65=-1.2628
area66_0=8.37;area66_212=14.56;dist66=524.45;  dx66=-56.47;dy66=-222.66;dphi66=-1.2625
area67_0=8.68;area67_212=14.76;dist67=524.30;  dx67=-56.81;dy67=-222.61;dphi67=-1.2632
area68_0=8.93;area68_212=14.64;dist68=524.48;  dx68=-56.26;dy68=-222.86;dphi68=-1.2622
area69_0=8.27;area69_212=14.42;dist69=524.43;  dx69=-56.28;dy69=-222.87;dphi69=-1.2620
area70_0=8.40;area70_212=14.57;dist70=524.45;  dx70=-56.40;dy70=-222.77;dphi70=-1.2620
area71_0=8.28;area71_212=14.70;dist71=524.44;  dx71=-56.29;dy71=-222.56;dphi71=-1.2622
area72_0=8.74;area72_212=14.46;dist72=524.39;  dx72=-56.50;dy72=-222.58;dphi72=-1.2625
area73_0=8.77;area73_212=14.48;dist73=524.47;  dx73=-56.58;dy73=-222.72;dphi73=-1.2627
area74_0=8.12;area74_212=15.40;dist74=524.49;  dx74=-56.38;dy74=-222.52;dphi74=-1.2623
area75_0=7.99;area75_212=14.53;dist75=524.58;  dx75=-56.39;dy75=-222.72;dphi75=-1.2624
area76_0=8.33;area76_212=15.21;dist76=524.64;  dx76=-56.35;dy76=-222.55;dphi76=-1.2620
area78_0=9.43;area78_212=14.51;dist78=524.52;  dx78=-56.45;dy78=-222.71;dphi78=-1.2623
area79_0=8.63;area79_212=14.56;dist79=524.47;  dx79=-56.49;dy79=-222.71;dphi79=-1.2622
area80_0=8.23;area80_212=14.36;dist80=524.42;  dx80=-56.64;dy80=-222.41;dphi80=-1.2630
area81_0=8.15;area81_212=14.43;dist81=524.52;  dx81=-56.58;dy81=-222.44;dphi81=-1.2624
area82_0=8.56;area82_212=14.86;dist82=524.48;  dx82=-56.33;dy82=-222.69;dphi82=-1.2622
area83_0=8.22;area83_212=14.41;dist83=524.32;  dx83=-56.30;dy83=-222.76;dphi83=-1.2621
area85_0=8.14;area85_212=15.38;dist85=524.41;  dx85=-56.09;dy85=-222.77;dphi85=-1.2619
area86_0=8.41;area86_212=14.45;dist86=524.49;  dx86=-56.64;dy86=-222.55;dphi86=-1.2630
area87_0=8.57;area87_212=14.70;dist87=524.38;  dx87=-56.65;dy87=-222.99;dphi87=-1.2625
area88_0=8.02;area88_212=14.46;dist88=524.56;  dx88=-56.62;dy88=-222.65;dphi88=-1.2632
area91_0=8.04;area91_212=14.49;dist91=524.55;  dx91=-56.72;dy91=-222.43;dphi91=-1.2632
area92_0=8.21;area92_212=14.80;dist92=524.39;  dx92=-56.48;dy92=-222.52;dphi92=-1.2627
area93_0=8.21;area93_212=14.43;dist93=524.53;  dx93=-56.77;dy93=-222.44;dphi93=-1.2635
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal44_edges.DAT' -A 350000" u (($1+dx44)*cos(dphi44)-($2+dy44)*sin(dphi44)):(($2+dy44)*cos(dphi44)+($1+dx44)*sin(dphi44)) w l title 'petal 44'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal45_edges.DAT' -A 350000" u (($1+dx45)*cos(dphi45)-($2+dy45)*sin(dphi45)):(($2+dy45)*cos(dphi45)+($1+dx45)*sin(dphi45)) w l title 'petal 45'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal46_edges.DAT' -A 350000" u (($1+dx46)*cos(dphi46)-($2+dy46)*sin(dphi46)):(($2+dy46)*cos(dphi46)+($1+dx46)*sin(dphi46)) w l title 'petal 46'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal47_edges.DAT' -A 350000" u (($1+dx47)*cos(dphi47)-($2+dy47)*sin(dphi47)):(($2+dy47)*cos(dphi47)+($1+dx47)*sin(dphi47)) w l title 'petal 47'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal48_edges.DAT' -A 350000" u (($1+dx48)*cos(dphi48)-($2+dy48)*sin(dphi48)):(($2+dy48)*cos(dphi48)+($1+dx48)*sin(dphi48)) w l title 'petal 48'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal49_edges.DAT' -A 350000" u (($1+dx49)*cos(dphi49)-($2+dy49)*sin(dphi49)):(($2+dy49)*cos(dphi49)+($1+dx49)*sin(dphi49)) w l title 'petal 49'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal50_edges.DAT' -A 350000" u (($1+dx50)*cos(dphi50)-($2+dy50)*sin(dphi50)):(($2+dy50)*cos(dphi50)+($1+dx50)*sin(dphi50)) w l title 'petal 50'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal51_edges.DAT' -A 350000" u (($1+dx51)*cos(dphi51)-($2+dy51)*sin(dphi51)):(($2+dy51)*cos(dphi51)+($1+dx51)*sin(dphi51)) w l title 'petal 51'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal52_edges.DAT' -A 350000" u (($1+dx52)*cos(dphi52)-($2+dy52)*sin(dphi52)):(($2+dy52)*cos(dphi52)+($1+dx52)*sin(dphi52)) w l title 'petal 52'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal53_edges.DAT' -A 350000" u (($1+dx53)*cos(dphi53)-($2+dy53)*sin(dphi53)):(($2+dy53)*cos(dphi53)+($1+dx53)*sin(dphi53)) w l title 'petal 53'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal54_edges.DAT' -A 350000" u (($1+dx54)*cos(dphi54)-($2+dy54)*sin(dphi54)):(($2+dy54)*cos(dphi54)+($1+dx54)*sin(dphi54)) w l title 'petal 54'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal55_edges.DAT' -A 350000" u (($1+dx55)*cos(dphi55)-($2+dy55)*sin(dphi55)):(($2+dy55)*cos(dphi55)+($1+dx55)*sin(dphi55)) w l title 'petal 55'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal57_edges.DAT' -A 350000" u (($1+dx57)*cos(dphi57)-($2+dy57)*sin(dphi57)):(($2+dy57)*cos(dphi57)+($1+dx57)*sin(dphi57)) w l title 'petal 57'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal58_edges.DAT' -A 350000" u (($1+dx58)*cos(dphi58)-($2+dy58)*sin(dphi58)):(($2+dy58)*cos(dphi58)+($1+dx58)*sin(dphi58)) w l title 'petal 58'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal59_edges.DAT' -A 350000" u (($1+dx59)*cos(dphi59)-($2+dy59)*sin(dphi59)):(($2+dy59)*cos(dphi59)+($1+dx59)*sin(dphi59)) w l title 'petal 59'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal60_edges.DAT' -A 350000" u (($1+dx60)*cos(dphi60)-($2+dy60)*sin(dphi60)):(($2+dy60)*cos(dphi60)+($1+dx60)*sin(dphi60)) w l title 'petal 60'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal61_edges.DAT' -A 350000" u (($1+dx61)*cos(dphi61)-($2+dy61)*sin(dphi61)):(($2+dy61)*cos(dphi61)+($1+dx61)*sin(dphi61)) w l title 'petal 61'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal62_edges.DAT' -A 350000" u (($1+dx62)*cos(dphi62)-($2+dy62)*sin(dphi62)):(($2+dy62)*cos(dphi62)+($1+dx62)*sin(dphi62)) w l title 'petal 62'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal63_edges.DAT' -A 350000" u (($1+dx63)*cos(dphi63)-($2+dy63)*sin(dphi63)):(($2+dy63)*cos(dphi63)+($1+dx63)*sin(dphi63)) w l title 'petal 63'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal64_edges.DAT' -A 350000" u (($1+dx64)*cos(dphi64)-($2+dy64)*sin(dphi64)):(($2+dy64)*cos(dphi64)+($1+dx64)*sin(dphi64)) w l title 'petal 64'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal65_edges.DAT' -A 350000" u (($1+dx65)*cos(dphi65)-($2+dy65)*sin(dphi65)):(($2+dy65)*cos(dphi65)+($1+dx65)*sin(dphi65)) w l title 'petal 65'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal66_edges.DAT' -A 350000" u (($1+dx66)*cos(dphi66)-($2+dy66)*sin(dphi66)):(($2+dy66)*cos(dphi66)+($1+dx66)*sin(dphi66)) w l title 'petal 66'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal67_edges.DAT' -A 350000" u (($1+dx67)*cos(dphi67)-($2+dy67)*sin(dphi67)):(($2+dy67)*cos(dphi67)+($1+dx67)*sin(dphi67)) w l title 'petal 67'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal68_edges.DAT' -A 350000" u (($1+dx68)*cos(dphi68)-($2+dy68)*sin(dphi68)):(($2+dy68)*cos(dphi68)+($1+dx68)*sin(dphi68)) w l title 'petal 68'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal69_edges.DAT' -A 350000" u (($1+dx69)*cos(dphi69)-($2+dy69)*sin(dphi69)):(($2+dy69)*cos(dphi69)+($1+dx69)*sin(dphi69)) w l title 'petal 69'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal70_edges.DAT' -A 350000" u (($1+dx70)*cos(dphi70)-($2+dy70)*sin(dphi70)):(($2+dy70)*cos(dphi70)+($1+dx70)*sin(dphi70)) w l title 'petal 70'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal71_edges.DAT' -A 350000" u (($1+dx71)*cos(dphi71)-($2+dy71)*sin(dphi71)):(($2+dy71)*cos(dphi71)+($1+dx71)*sin(dphi71)) w l title 'petal 71'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal72_edges.DAT' -A 350000" u (($1+dx72)*cos(dphi72)-($2+dy72)*sin(dphi72)):(($2+dy72)*cos(dphi72)+($1+dx72)*sin(dphi72)) w l title 'petal 72'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal73_edges.DAT' -A 350000" u (($1+dx73)*cos(dphi73)-($2+dy73)*sin(dphi73)):(($2+dy73)*cos(dphi73)+($1+dx73)*sin(dphi73)) w l title 'petal 73'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal74_edges.DAT' -A 350000" u (($1+dx74)*cos(dphi74)-($2+dy74)*sin(dphi74)):(($2+dy74)*cos(dphi74)+($1+dx74)*sin(dphi74)) w l title 'petal 74'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal75_edges.DAT' -A 350000" u (($1+dx75)*cos(dphi75)-($2+dy75)*sin(dphi75)):(($2+dy75)*cos(dphi75)+($1+dx75)*sin(dphi75)) w l title 'petal 75'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal76_edges.DAT' -A 350000" u (($1+dx76)*cos(dphi76)-($2+dy76)*sin(dphi76)):(($2+dy76)*cos(dphi76)+($1+dx76)*sin(dphi76)) w l title 'petal 76'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal78_edges.DAT' -A 350000" u (($1+dx78)*cos(dphi78)-($2+dy78)*sin(dphi78)):(($2+dy78)*cos(dphi78)+($1+dx78)*sin(dphi78)) w l title 'petal 78'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal79_edges.DAT' -A 350000" u (($1+dx79)*cos(dphi79)-($2+dy79)*sin(dphi79)):(($2+dy79)*cos(dphi79)+($1+dx79)*sin(dphi79)) w l title 'petal 79'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal80_edges.DAT' -A 350000" u (($1+dx80)*cos(dphi80)-($2+dy80)*sin(dphi80)):(($2+dy80)*cos(dphi80)+($1+dx80)*sin(dphi80)) w l title 'petal 80'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal81_edges.DAT' -A 350000" u (($1+dx81)*cos(dphi81)-($2+dy81)*sin(dphi81)):(($2+dy81)*cos(dphi81)+($1+dx81)*sin(dphi81)) w l title 'petal 81'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal82_edges.DAT' -A 350000" u (($1+dx82)*cos(dphi82)-($2+dy82)*sin(dphi82)):(($2+dy82)*cos(dphi82)+($1+dx82)*sin(dphi82)) w l title 'petal 82'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal83_edges.DAT' -A 350000" u (($1+dx83)*cos(dphi83)-($2+dy83)*sin(dphi83)):(($2+dy83)*cos(dphi83)+($1+dx83)*sin(dphi83)) w l title 'petal 83'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal85_edges.DAT' -A 350000" u (($1+dx85)*cos(dphi85)-($2+dy85)*sin(dphi85)):(($2+dy85)*cos(dphi85)+($1+dx85)*sin(dphi85)) w l title 'petal 85'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal86_edges.DAT' -A 350000" u (($1+dx86)*cos(dphi86)-($2+dy86)*sin(dphi86)):(($2+dy86)*cos(dphi86)+($1+dx86)*sin(dphi86)) w l title 'petal 86'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal87_edges.DAT' -A 350000" u (($1+dx87)*cos(dphi87)-($2+dy87)*sin(dphi87)):(($2+dy87)*cos(dphi87)+($1+dx87)*sin(dphi87)) w l title 'petal 87'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal88_edges.DAT' -A 350000" u (($1+dx88)*cos(dphi88)-($2+dy88)*sin(dphi88)):(($2+dy88)*cos(dphi88)+($1+dx88)*sin(dphi88)) w l title 'petal 88'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal91_edges.DAT' -A 350000" u (($1+dx91)*cos(dphi91)-($2+dy91)*sin(dphi91)):(($2+dy91)*cos(dphi91)+($1+dx91)*sin(dphi91)) w l title 'petal 91'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal92_edges.DAT' -A 350000" u (($1+dx92)*cos(dphi92)-($2+dy92)*sin(dphi92)):(($2+dy92)*cos(dphi92)+($1+dx92)*sin(dphi92)) w l title 'petal 92'
plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal93_edges.DAT' -A 350000" u (($1+dx93)*cos(dphi93)-($2+dy93)*sin(dphi93)):(($2+dy93)*cos(dphi93)+($1+dx93)*sin(dphi93)) w l title 'petal 93'

plot  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal44_edges.DAT' -A 350000" u (($1+dx44)*cos(dphi44)-($2+dy44)*sin(dphi44)):(($2+dy44)*cos(dphi44)+($1+dx44)*sin(dphi44)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal45_edges.DAT' -A 350000" u (($1+dx45)*cos(dphi45)-($2+dy45)*sin(dphi45)):(($2+dy45)*cos(dphi45)+($1+dx45)*sin(dphi45)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal46_edges.DAT' -A 350000" u (($1+dx46)*cos(dphi46)-($2+dy46)*sin(dphi46)):(($2+dy46)*cos(dphi46)+($1+dx46)*sin(dphi46)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal47_edges.DAT' -A 350000" u (($1+dx47)*cos(dphi47)-($2+dy47)*sin(dphi47)):(($2+dy47)*cos(dphi47)+($1+dx47)*sin(dphi47)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal48_edges.DAT' -A 350000" u (($1+dx48)*cos(dphi48)-($2+dy48)*sin(dphi48)):(($2+dy48)*cos(dphi48)+($1+dx48)*sin(dphi48)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal49_edges.DAT' -A 350000" u (($1+dx49)*cos(dphi49)-($2+dy49)*sin(dphi49)):(($2+dy49)*cos(dphi49)+($1+dx49)*sin(dphi49)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal50_edges.DAT' -A 350000" u (($1+dx50)*cos(dphi50)-($2+dy50)*sin(dphi50)):(($2+dy50)*cos(dphi50)+($1+dx50)*sin(dphi50)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal51_edges.DAT' -A 350000" u (($1+dx51)*cos(dphi51)-($2+dy51)*sin(dphi51)):(($2+dy51)*cos(dphi51)+($1+dx51)*sin(dphi51)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal52_edges.DAT' -A 350000" u (($1+dx52)*cos(dphi52)-($2+dy52)*sin(dphi52)):(($2+dy52)*cos(dphi52)+($1+dx52)*sin(dphi52)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal53_edges.DAT' -A 350000" u (($1+dx53)*cos(dphi53)-($2+dy53)*sin(dphi53)):(($2+dy53)*cos(dphi53)+($1+dx53)*sin(dphi53)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal54_edges.DAT' -A 350000" u (($1+dx54)*cos(dphi54)-($2+dy54)*sin(dphi54)):(($2+dy54)*cos(dphi54)+($1+dx54)*sin(dphi54)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal55_edges.DAT' -A 350000" u (($1+dx55)*cos(dphi55)-($2+dy55)*sin(dphi55)):(($2+dy55)*cos(dphi55)+($1+dx55)*sin(dphi55)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal57_edges.DAT' -A 350000" u (($1+dx57)*cos(dphi57)-($2+dy57)*sin(dphi57)):(($2+dy57)*cos(dphi57)+($1+dx57)*sin(dphi57)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal58_edges.DAT' -A 350000" u (($1+dx58)*cos(dphi58)-($2+dy58)*sin(dphi58)):(($2+dy58)*cos(dphi58)+($1+dx58)*sin(dphi58)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal59_edges.DAT' -A 350000" u (($1+dx59)*cos(dphi59)-($2+dy59)*sin(dphi59)):(($2+dy59)*cos(dphi59)+($1+dx59)*sin(dphi59)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal60_edges.DAT' -A 350000" u (($1+dx60)*cos(dphi60)-($2+dy60)*sin(dphi60)):(($2+dy60)*cos(dphi60)+($1+dx60)*sin(dphi60)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal61_edges.DAT' -A 350000" u (($1+dx61)*cos(dphi61)-($2+dy61)*sin(dphi61)):(($2+dy61)*cos(dphi61)+($1+dx61)*sin(dphi61)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal62_edges.DAT' -A 350000" u (($1+dx62)*cos(dphi62)-($2+dy62)*sin(dphi62)):(($2+dy62)*cos(dphi62)+($1+dx62)*sin(dphi62)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal63_edges.DAT' -A 350000" u (($1+dx63)*cos(dphi63)-($2+dy63)*sin(dphi63)):(($2+dy63)*cos(dphi63)+($1+dx63)*sin(dphi63)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal64_edges.DAT' -A 350000" u (($1+dx64)*cos(dphi64)-($2+dy64)*sin(dphi64)):(($2+dy64)*cos(dphi64)+($1+dx64)*sin(dphi64)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal65_edges.DAT' -A 350000" u (($1+dx65)*cos(dphi65)-($2+dy65)*sin(dphi65)):(($2+dy65)*cos(dphi65)+($1+dx65)*sin(dphi65)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal66_edges.DAT' -A 350000" u (($1+dx66)*cos(dphi66)-($2+dy66)*sin(dphi66)):(($2+dy66)*cos(dphi66)+($1+dx66)*sin(dphi66)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal67_edges.DAT' -A 350000" u (($1+dx67)*cos(dphi67)-($2+dy67)*sin(dphi67)):(($2+dy67)*cos(dphi67)+($1+dx67)*sin(dphi67)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal68_edges.DAT' -A 350000" u (($1+dx68)*cos(dphi68)-($2+dy68)*sin(dphi68)):(($2+dy68)*cos(dphi68)+($1+dx68)*sin(dphi68)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal69_edges.DAT' -A 350000" u (($1+dx69)*cos(dphi69)-($2+dy69)*sin(dphi69)):(($2+dy69)*cos(dphi69)+($1+dx69)*sin(dphi69)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal70_edges.DAT' -A 350000" u (($1+dx70)*cos(dphi70)-($2+dy70)*sin(dphi70)):(($2+dy70)*cos(dphi70)+($1+dx70)*sin(dphi70)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal71_edges.DAT' -A 350000" u (($1+dx71)*cos(dphi71)-($2+dy71)*sin(dphi71)):(($2+dy71)*cos(dphi71)+($1+dx71)*sin(dphi71)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal72_edges.DAT' -A 350000" u (($1+dx72)*cos(dphi72)-($2+dy72)*sin(dphi72)):(($2+dy72)*cos(dphi72)+($1+dx72)*sin(dphi72)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal73_edges.DAT' -A 350000" u (($1+dx73)*cos(dphi73)-($2+dy73)*sin(dphi73)):(($2+dy73)*cos(dphi73)+($1+dx73)*sin(dphi73)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal74_edges.DAT' -A 350000" u (($1+dx74)*cos(dphi74)-($2+dy74)*sin(dphi74)):(($2+dy74)*cos(dphi74)+($1+dx74)*sin(dphi74)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal75_edges.DAT' -A 350000" u (($1+dx75)*cos(dphi75)-($2+dy75)*sin(dphi75)):(($2+dy75)*cos(dphi75)+($1+dx75)*sin(dphi75)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal76_edges.DAT' -A 350000" u (($1+dx76)*cos(dphi76)-($2+dy76)*sin(dphi76)):(($2+dy76)*cos(dphi76)+($1+dx76)*sin(dphi76)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal78_edges.DAT' -A 350000" u (($1+dx78)*cos(dphi78)-($2+dy78)*sin(dphi78)):(($2+dy78)*cos(dphi78)+($1+dx78)*sin(dphi78)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal79_edges.DAT' -A 350000" u (($1+dx79)*cos(dphi79)-($2+dy79)*sin(dphi79)):(($2+dy79)*cos(dphi79)+($1+dx79)*sin(dphi79)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal80_edges.DAT' -A 350000" u (($1+dx80)*cos(dphi80)-($2+dy80)*sin(dphi80)):(($2+dy80)*cos(dphi80)+($1+dx80)*sin(dphi80)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal81_edges.DAT' -A 350000" u (($1+dx81)*cos(dphi81)-($2+dy81)*sin(dphi81)):(($2+dy81)*cos(dphi81)+($1+dx81)*sin(dphi81)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal82_edges.DAT' -A 350000" u (($1+dx82)*cos(dphi82)-($2+dy82)*sin(dphi82)):(($2+dy82)*cos(dphi82)+($1+dx82)*sin(dphi82)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal83_edges.DAT' -A 350000" u (($1+dx83)*cos(dphi83)-($2+dy83)*sin(dphi83)):(($2+dy83)*cos(dphi83)+($1+dx83)*sin(dphi83)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal85_edges.DAT' -A 350000" u (($1+dx85)*cos(dphi85)-($2+dy85)*sin(dphi85)):(($2+dy85)*cos(dphi85)+($1+dx85)*sin(dphi85)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal86_edges.DAT' -A 350000" u (($1+dx86)*cos(dphi86)-($2+dy86)*sin(dphi86)):(($2+dy86)*cos(dphi86)+($1+dx86)*sin(dphi86)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal87_edges.DAT' -A 350000" u (($1+dx87)*cos(dphi87)-($2+dy87)*sin(dphi87)):(($2+dy87)*cos(dphi87)+($1+dx87)*sin(dphi87)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal88_edges.DAT' -A 350000" u (($1+dx88)*cos(dphi88)-($2+dy88)*sin(dphi88)):(($2+dy88)*cos(dphi88)+($1+dx88)*sin(dphi88)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal91_edges.DAT' -A 350000" u (($1+dx91)*cos(dphi91)-($2+dy91)*sin(dphi91)):(($2+dy91)*cos(dphi91)+($1+dx91)*sin(dphi91)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal92_edges.DAT' -A 350000" u (($1+dx92)*cos(dphi92)-($2+dy92)*sin(dphi92)):(($2+dy92)*cos(dphi92)+($1+dx92)*sin(dphi92)) w l notitle,\
  "<grep 'Circle     7' '/Users/rcorliss/Desktop/Output.Files.3/petal93_edges.DAT' -A 350000" u (($1+dx93)*cos(dphi93)-($2+dy93)*sin(dphi93)):(($2+dy93)*cos(dphi93)+($1+dx93)*sin(dphi93)) w l notitle
